name: Build and Deploy

on:
  push:
    branches: auto-deploy

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Project Dependencies
        run: npm ci

      - name: Build & deploy
        run: npm run build --verbose --log-pages
